### ISSUE TITLE
Bug: Silently dropping events without errors/logging

### ISSUE THREAD

**Issue by megatron10** [julien-duponchelle/python-mysql-replication#483]
I found a bug in the client. This causes it to drop events from relevant tables and schemas due to handling of rotate events. There is no error logging indicating that an event from a relevant table is being dropped either.

Consider the following usual sequence of binlog file events:
1. TableMapEvent table_id: 1, table_name: test_table, schema_name: test_schema
2. InsertRowEvent table_id:1, .....

The erroneous library flow:
1. BinLogStreamReader correctly parses the table map event, updates the table map entry for the table.
2. When fetching the next event in fetchone(), pymysql.OperationalError happens with an expected error code:
https://github.com/julien-duponchelle/python-mysql-replication/blob/a3015964398fbbf5ad343feaec02f64b17957ab8/pymysqlreplication/binlogstream.py#L573-L595
3. As per the exception handling, the flow continues in the while loop. In the next iteration we establish a new connection.
4. BinLogStreamReader gets a Fake Rotate Event after establishing the connection: https://mariadb.com/kb/en/fake-rotate_event/#:~:text=When%20a%20slave%20server%20connects,file%20name%20of%20the%20master.
5. The `table_map` gets invalidated on every Rotate Event, this causes us to forget the Table Map entry we parsed prior to the connection issue. https://github.com/julien-duponchelle/python-mysql-replication/blob/a3015964398fbbf5ad343feaec02f64b17957ab8/pymysqlreplication/binlogstream.py#L621-L633
6. Next we get the InsertRowEvent, but we don't have the table id available in the `table_map`, this causes a KeyError while constructing the Event object, and the event gets dropped silently, despite being of interest. In the __init__ method of the parent class `RowsEvent`, we encounter a KeyError while looking up the table_map, the implementation here marks this event as not to be processed: `self._processed = False`.
https://github.com/julien-duponchelle/python-mysql-replication/blob/a3015964398fbbf5ad343feaec02f64b17957ab8/pymysqlreplication/row_event.py#L32-L38
7. One level higher, the BinLogPacketWrapper (this invokes the event object construction) sets the event object to None:
https://github.com/julien-duponchelle/python-mysql-replication/blob/a3015964398fbbf5ad343feaec02f64b17957ab8/pymysqlreplication/packet.py#L149-L165
8. Back to the BinLogStreamReader, it silently ignores the event because it has no information about it, except the next log position. It moves ahead the log position, and then ignores the event and moves forward.
https://github.com/julien-duponchelle/python-mysql-replication/blob/a3015964398fbbf5ad343feaec02f64b17957ab8/pymysqlreplication/binlogstream.py#L634-L635
https://github.com/julien-duponchelle/python-mysql-replication/blob/a3015964398fbbf5ad343feaec02f64b17957ab8/pymysqlreplication/binlogstream.py#L679-L684

Potential fix strategies:
- We could retain the old log position in-case the event parsed was a table map event, and use that as the start point for the new connection, as the context is necessary.
- We could be smarter about resetting the `table_map`, detecting whether the event is an actual rotate or fake rotate seems easy based on the docs.
- I maybe missing something here, but just don't reset the `table_map`. I don't completely understand the reason for resetting the table map. We could store the table and schema name in the table_map, and use that while processing the TableMapEvent. After DB restart if the DB remaps the tables to different ids, we would get TableMapEvents for it. Shouldn't these events be enough to fix the `table_map` prior to the Row based events? Why do we need to actually reset the `table_map`?

Some other points to note:
- It'd be nice to add some logging to the library so such behaviour can be easily detected by the end users.
- Establishing connections in an infinite loop without any backoff doesn't seem right, might worsen the situation if failures are happening due to load on the database.

**Comment by sean-k1** [comment]
@megatron10 what is your mysql Version? If your Mysql version is 8.0,
check this [one](https://github.com/julien-duponchelle/python-mysql-replication/pull/446#issuecomment-1727045872) 
we always update table_map when Before InsertRowEvent occured

**Comment by megatron10** [comment]
The issue is not based on how we extract information from the TableMapEvent. The `table_map` does get updated, but when the connection is dropped after a TableMapEvent, the client re-establishes the connection and gets a (Fake) RotateEvent. The RotateEvent handling clears the table map.
https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/blob/9c781b5cedc70ee62dd24c18573746079ec43792/pymysqlreplication/binlogstream.py#L575-L635

**Comment by sean-k1** [comment]
@megatron10 
understand this one!
thanks for writing detailed issue problem!

**Comment by sean-k1** [comment]
@megatron10 
I added logging through your good words.
Finding the table_map by name when a fake rotate event occurs is something I need to think about a bit more.
