### ISSUE TITLE
Add 'hacktoberfest' Topic to Repository for Hacktoberfest 2023 Participation

### ISSUE THREAD

**Issue by dongwook-chan** [julien-duponchelle/python-mysql-replication#493]
@julien-duponchelle 

I wanted to discuss the possibility of prepping the python-mysql-replication repository for participation in Hacktoberfest 2023.

To ensure our project is discoverable to potential contributors during Hacktoberfest, we need to add the hacktoberfest topic to our repository. This will undoubtedly enhance our visibility and possibly bring in new and enthusiastic contributors to our project.

To add the topic:

1. Navigate to the main page of the repository.
2. Under the "About" section, click "⚙️"
3. Append 'hacktoberfest' with space separator.
4. Click "Save changes."

This seems to require 'Admin' level authority, and can only be carried out by you. Thank you in advance for considering this request.

**Comment by julien-duponchelle** [comment]
Should be good : https://github.com/julien-duponchelle/python-mysql-replication/discussions/492
