### ISSUE TITLE
delete Unknown variable 

### ISSUE THREAD

**Issue by sean-k1** [julien-duponchelle/python-mysql-replication#517]
Problem
---

packet.py file 84 line  typo exists.
```
raise ValueError("Json type %d is not handled" % t)
```
we need to change t => type.

**Comment by Tashuuuu** [comment]
This change has been made already.

<img width="443" alt="image" src="https://github.com/julien-duponchelle/python-mysql-replication/assets/85075827/fe3e41c8-89d9-440a-b3d2-ef2922694698">

**Comment by sean-k1** [comment]
@Tashuuuu Thanks let me know.
I did not know this already changed.
