### ISSUE TITLE
Unknown variable

### ISSUE THREAD

**Issue by sean-k1** [julien-duponchelle/python-mysql-replication#520]
Description
---
 row_event.py 89Lines

```
        # etc
        else:
            self.extra_data = self.packet.read(self.extra_info_length - 3)
```
I think It is really rare case.
but we should change extra_info_length => extra_data_length

We don't have this extra_info_length value.
May be typo Issue..

**Comment by swatichauhan814** [comment]
Hi, 
I would like to work on this ? Can you assign this to me ?

**Comment by sean-k1** [comment]
@swatichauhan814 
Sure Thanks!
