### ISSUE TITLE
Fix TestCode Using Constant instead String

### ISSUE THREAD

**Issue by sean-k1** [julien-duponchelle/python-mysql-replication#552]
Comparing through constants is better than comparing strings directly

https://github.com/julien-duponchelle/python-mysql-replication/blob/c639f4714956816e3f9b529596e2268caef8daac/pymysqlreplication/tests/test_basic.py#L1793C3-L1793C3

"null" -> NONE_SOURCE.NULL

https://github.com/julien-duponchelle/python-mysql-replication/blob/c639f4714956816e3f9b529596e2268caef8daac/pymysqlreplication/tests/test_basic.py#L1826-L1838

"null" -> NONE_SOURCE.NULL
"out of datetime2 range" -> NONE_SOURCE.OUT_OF_DATETIME2_RANGE
"out of datetime range" -> NONE_SOURCE.OUT_OF_DATETIME_RANGE

**Comment by sotiriszogos** [comment]
Hello, can I work on that?

**Comment by sean-k1** [comment]
@sotiriszogos sure thanks!
