### ISSUE TITLE
contribution section in README.md

### ISSUE THREAD

**Issue by Rjchauhan18** [julien-duponchelle/python-mysql-replication#554]
## **Description**

The community of [python-mysql-replication](https://github.com/julien-duponchelle/python-mysql-replication)  has grown larger . It will be good have a contribution section in README.md file to incourage contributors and motivate everyone.

@julien-duponchelle , I suggest to have contribution section like this in README.md file .
Please assign this to me

## 👥 Contributors

<div align="center">
  <a href="https://github.com/julien-duponchelle/python-mysql-replication/graphs/contributors">
    <img src="https://contrib.rocks/image?repo=julien-duponchelle/python-mysql-replication&max=400&columns=10" style="margin: 5px;" />
  </a>
  <p>Join our community and become a contributor today! 🚀 </p>
</div>

**Comment by julien-duponchelle** [comment]
Hello,

Their is already a contributor section with some additional details:
https://github.com/julien-duponchelle/python-mysql-replication#contributors

Their is few people missing right now from the summer contributions
