### ISSUE TITLE
Change read.me file Url link

### ISSUE THREAD

**Issue by sean-k1** [julien-duponchelle/python-mysql-replication#555]
We need to Change Url

Below change log should be change

Changelog
---

https://github.com/noplay/python-mysql-replication/blob/master/CHANGELOG

to 

https://github.com/noplay/python-mysql-replication/blob/main/CHANGELOG

And 

Below Examples Lines link 

Examples
---
All examples are available in the [examples directory](https://github.com/noplay/python-mysql-replication/tree/master/examples)

This link should be change 

https://github.com/noplay/python-mysql-replication/tree/master/examples  

to

https://github.com/noplay/python-mysql-replication/tree/main/examples

**Comment by kunaldhand** [comment]
Only need to change README.md? Assign this to me, I would like to work on this. @sean-k1

**Comment by sean-k1** [comment]
@kunaldhand yes just read me file thanks
