### ISSUE TITLE
Strange error in event_row.py

### ISSUE THREAD

**Issue by bohnster** [julien-duponchelle/python-mysql-replication#56]
Hi,

Nice library. 

Here is a problem that has started happening, and I don't know why. Here is the Python error:

 File "/usr/lib/python2.6/site-packages/pymysqlreplication/binlogstream.py", line 146, in fetchone
    self.**use_checksum)
  File "/usr/lib/python2.6/site-packages/pymysqlreplication/packet.py", line 93, in __init**
    ctl_connection)
  File "/usr/lib/python2.6/site-packages/pymysqlreplication/row_event.py", line 491, in **init**
    column_schema = self.column_schemas[i]
IndexError: tuple index out of range

I think this is due to some MySQL internal query that pymysqlreplication has trouble with. The EventType that appears to trigger the failure is a QueryEvent, but the event is an internal MySQL event. Here some events that occur just before the failure. You can see that these are internal MySQL queries:

=== QueryEvent ===
Date: 2013-12-11T16:31:15
Log position: 30510
Event size: 80
Read bytes: 80
Schema: mysql
Execution time: 0
Query: TRUNCATE TABLE time_zone_transition
=== QueryEvent ===
Date: 2013-12-11T16:31:15
Log position: 30614
Event size: 85
Read bytes: 85
Schema: mysql
Execution time: 0
Query: TRUNCATE TABLE time_zone_transition_type
=== QueryEvent ===
Date: 2013-12-11T16:31:15
Log position: 30683
Event size: 50
Read bytes: 50
Schema: mysql
Execution time: 0
Query: BEGIN

^^ error occurs immediately after this

You can see that the date is 2013.12.11.

I looked at the source code where the error occurs:

485        for i in range(0, len(column_types)):
486            column_type = column_types[i]
487            column_schema = self.column_schemas[i]
488            col = Column(byte2int(column_type), column_schema, from_packet)
489            self.columns.append(col)

The problem is that self.column_schemas is None, so index fails. 

Any ideas on this? Thanks.

**Comment by dmariassy** [comment]
Hi,

and thanks for the very handy library! 👍

Although this thread has been closed for a while, I think that the issue pointed out by @banks continues to pose a serious problem for many potential users. The ability to reliably replay events that were created before the streaming process started (or while the process was temporarily down) is required in almost all real-world use-cases.

But I think that adding this functionality would not be that difficult if we (as suggested by banks and implemented by [debezium.io](http://debezium.io/blog/2016/04/15/parsing-ddl/)):

1. Captured QueryEvents that changed the underlying schema,
2. Executed the statements on a second MySQL instance,
3. Pointed the BinLogStreamReader's __get_table_information method to this server for table mapping.

This way, the RowEvent that is currently being processed would be always validated against the schema that was in place at the time of its creation.

As a matter of fact, this is the design I followed when monkey-pathching your library, which is now used in production at our company :)

I have taken a few minutes to apply these changes to your project's source code and would be happy to submit a PR if you think that adding this feature would be useful.

However, I have not yet come up with a way that would allow me to test this feature in _your_ environment. We're using a pretty different test set-up, which includes all the components we use in our data pipeline, and I wouldn't be able to simply transfer our scripts to your CI env. In any case, I think that testing this feature would require using Docker, Vagrant or some other tool that allows for the total sandboxing of components given the necessity to launch two MySQL servers.

Let me know what you think!

**Comment by banks** [comment]
Nitpick:

> as suggested by banks and implemented by debezium.io

Debezium actually don't use a second MySQL instance but rolled their own MySQL DDL parser and build schema mappings  that way. It's nice in that they don't need operational complexity of a MySQL instance to manage schemas, but like the Yelp guys I was always wary of the effort required to do that and keep it perfectly in sync and bug free compared to MySQL releases/behaviour. I can't comment on their implementation though.

Just a note if anyone else does dig up this thread...

**Comment by noplay** [comment]
Deploying a second instance seem not possible for some people.  Do you think it's possible to implement it as an optionnal behavior?

**Comment by banks** [comment]
This is an old closed thread if you heave feature suggestions the authors are more likely to notice on a new issue...

FWIW what I described above and Yelp mentioned recently is not really a "second instance" - there is no copy of the data. It's just a way to parse the schema changes in DDL statements without rolling your own parser. 

If you really don't like the overhead of that solution, debezium.io already rolled the other one.

Also I think python-MySQL-replication is too low level for this kind of feature as I mentioned - I suggest you check out a higher level framework like debezium if you don't want to build that stuff out yourself.

**Comment by felexkemboi** [comment]
Is there a way I can get the raw sql queries so that i can replay again for postresql

**Comment by noplay** [comment]
It's depends how you configure mysql if you want to get the raw query you
need to ask mysql to do the replication using query instead of raw data.

If you want to replicate to postgresql use pg chameleon it's a tool build
on top on this made to do that.

**Comment by felexkemboi** [comment]
My problem is  would like to get the raw queries then consume them.Like get the raw sql queries then write those queries in  another database

**Comment by felexkemboi** [comment]
`=== WriteRowsEvent ===
Date: 2019-06-28T03:21:53
Log position: 1838
Event size: 35
Read bytes: 12
Table: student.marks
Affected columns: 5
Changed rows: 1
Values:
`
this is the output i am getting when i run my script.I would love to extract the raw sql query that did that change
