### ISSUE TITLE
How to use auto_position ?

### ISSUE THREAD

**Issue by larzwow** [julien-duponchelle/python-mysql-replication#576]
Because I want to ensure the function of breakpoint continuation, I used this parameter.

auto_position: Use master_ Auto_ Position gtid to set position

Is this parameter written directly in the following format?

Auto_ Position="e53937be cdd7-11ea-840f-b02628fc286a: 1-10593571"

Can gtid be dynamically obtained

**Comment by jaehyeonpy** [comment]
Hello, I want to check if this is your intention:

1. giving the string format to auto_position

2. getting gtid as python-mysql-replication fetches event from database

**Comment by dongwook-chan** [comment]
> Is this parameter written directly in the following format?

Yes, but without any spaces.
`"e53937becdd7-11ea-840f-b02628fc286a:1-10593571"`

> Can gtid be dynamically obtained?

1. Using a MySQL client
`SHOW MASTER STATUS` command displays the current GTID.

2. From instances of GtidEvent
A `GtidEvent` is the first event in every transaction. 
This event has `gtid` as instance variable.
Subsequent events within the same transaction share the same GTID.

> I want to ensure the function of breakpoint continuation

GTID corresponds to a transaction not an event.
Transactions typically comprise multiple events.
If you want to resume a replication stream without processing any duplicate events,
it's important to track both the **GTID** and the **event sequence number within the transaction**.
This way, you can resume the stream precisely at the point it was interrupted, avoiding the processing of duplicate events.

**Comment by larzwow** [comment]
Thank you very much for your help Can this parameter be configured with multiple gtids like the following example:

auto_position="7317598d-bc76-11ec-b75a-005056bb8027:1-144522,
96985a5b-fd54-11e9-b5d6-b42e996db34a:1-12272,
9be85126-bc79-11ec-8604-005056bbaf47:1-3450030"

**Comment by larzwow** [comment]
> Author
@dongwook-chan 
how to ensure that this GTID will be updated in real-time? For example, if I have already processed the event event, how can this GTID be updated?

**Comment by larzwow** [comment]
@dongwook-chan Good afternoon, thank you for your help.

When I use gtid, after shutting down and restarting, this issue is reported. What I can confirm is that the number of days the binglog log server is retained is 30 days.

--- 
pymysql.err.OperationalError: (1236, "Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID set sent by the slave is 'c76d62ce-8075-11eb-a0f8-b02628fc286a:13590524910', and the missing transactions are 'c76d62ce-8075-11eb-a0f8-b02628fc286a:1-12585696247,\ne53937be-cdd7-11ea-840f-b02628fc286a:1-10593571'")

**Comment by larzwow** [comment]
已解决,so easy
