### ISSUE TITLE
[readme]  mysql-server-settings part has a deprecated variable

### ISSUE THREAD

**Issue by gongyisheng** [julien-duponchelle/python-mysql-replication#577]
Hi, I'm setting up binlog subscription using this package and I notice that the [mysql-server-settings](https://github.com/julien-duponchelle/python-mysql-replication#mysql-server-settings) part contains a deprecated variable. 

mysql version: >8.0

Quote from mysql doc: 
>[expire_logs_days](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_expire_logs_days) is deprecated, and you should expect it to be removed in a future release. Instead, use [binlog_expire_logs_seconds](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_expire_logs_seconds), which sets the binary log expiration period in seconds.

**Comment by sean-k1** [comment]
@gongyisheng 
Hello Thanks for reporting

Cool
I think it would be good to fix the readme with binlog_expire_log_seconds, which has been replaced since Mysql 8.0.

Would you be willing to work on this issue?

**Comment by gongyisheng** [comment]
Hi @sean-k1, sure, I can help submit a PR to fix it.

**Comment by sean-k1** [comment]
@gongyisheng I assgined you thnaks!
