### ISSUE TITLE
Bug in f-string formatting

### ISSUE THREAD

**Issue by AdrienPensart** [julien-duponchelle/python-mysql-replication#614]
In the last version, there is an issue introduced here : 

https://github.com/julien-duponchelle/python-mysql-replication/commit/0e31c58815f8c03b1eb93d9519ab71fc4268c8e9

Those slave_uuid should be quoted !
Or else, replication events like this SET will crash the loop stream.

**Comment by julien-duponchelle** [comment]
Thanks , are you happy to provide a PR?

**Comment by AdrienPensart** [comment]
Of course ;) 

https://github.com/julien-duponchelle/python-mysql-replication/pull/615

**Comment by sean-k1** [comment]
@AdrienPensart could you make pr for this issue

**Comment by julien-duponchelle** [comment]
Thanks a lot fix merged and released
